### ISSUE TITLE
Dispatch notification issue

### ISSUE THREAD

**Issue by SeanMcG2255** [JayseeXD/RRP_Organisation#43]
![Screenshot (437)](https://user-images.githubusercontent.com/101068332/157106687-13226e7e-870f-4bb1-8a09-dd29683bfb39.png)
![Screenshot (444)](https://user-images.githubusercontent.com/101068332/157106695-f242eb44-684e-402a-bca0-43f388d6c6cb.png)

Picture 1 shows the " Profile " Is layla rose when its not. ( Tony Banks was using the F10 disbatch Function )
Picture 2 shows Tina Yeller as a Police officer and Samuels as an EMS? also the Mechanics have Gray trackers now and are visable on the map. The numbers in the bottom right corner im not too sure if they are supposed to represent how many are on duty or not but its a bit messed up )

**Comment by xFutte** [comment]
Should be fixed after swapping to qb-dispatch
