### ISSUE TITLE
Locked in Door Cam view

### ISSUE THREAD

**Issue by xFutte** [JayseeXD/RRP_Organisation#58]
**Description**: 
I accidentally went into the door camera of my house instead of exiting the door and got locked in the camera unable to leave the camera.

**Expectations**: 
Was hoping to just be able to exit the camera like normal.

**Reproduction**: 
Unknown, I would assume using any house door camera could potentially initiate the bug.

**Attachments**: Picture of F8 provided

**Discord username**: 
Halfrican#0168

![image](https://user-images.githubusercontent.com/6727484/162284499-8b48a7b5-6c06-4a53-b147-8d26bfe8f109.png)

**Comment by JayseeXD** [comment]
Nil value was an unusual case which cannot be replicated, added a nil check to regest "closesthouse" should this ever happen again.
