### ISSUE TITLE
Freezing from going into pockets

### ISSUE THREAD

**Issue by xFutte** [JayseeXD/RRP_Organisation#61]
**Describe the bug:** 
I try to press my f2 to open my pockets, but when i do they dont open up, i am "frozen" and can't do anything. I tried clearing my cache multiple times and yet it keeps happening.

**Expected result:** 
I expected that clearing cache and restarting fivem should work, but it keeps happening

**How to reproduce:** 
I am not sure how to reproduce it

**Attachment** 
the f8 shows just the compass, nothing else about pockets/inventory

![image](https://user-images.githubusercontent.com/6727484/162578656-92432d9e-10bf-4b40-87d3-e6b707700e02.png)
![image](https://user-images.githubusercontent.com/6727484/162578649-725e16f6-3049-4e8a-8147-291c968e7935.png)

Discord username: Jekyll Hyde#8801

**Comment by JayseeXD** [comment]
Updated compass & hud - watch this ongoing
