### ISSUE TITLE
Sell drugs vehicle spam.

### ISSUE THREAD

**Issue by xFutte** [JayseeXD/RRP_Organisation#62]
**Describe the bug**
If corner selling and you hop in vehicle without stopping your corner selling it will spam you with cannot sell drugs yet.

**Expected result:**
What did you expect to happen? Upon entering a vehicle I'd expect it to auto cancel your corner selling.

**How to reproduce:**
How can the bug be reproduced? Corner sell with drugs in your inventory and hop in a vehicle, if you hop out it will continue to spam messages.

**Attachments**
Not sure if it's related or from harvesting plants but this is what I have: 
https://i.imgur.com/k8ttIXy.png    https://i.imgur.com/1x23rAV.png https://i.imgur.com/Zm6TBBL.png

**Discord username**
Most Palone

**Comment by JayseeXD** [comment]
Will now correctly cancel cornerselling when you get in a vehicle
